### ISSUE TITLE
Support PDF output

### ISSUE THREAD

**Issue by sschuhmann** [LaurentRDC/pandoc-plot#11]
I was unable to produce a PDF with replaced graphs in the current version. However the html output worked really good. 

It would be nice to have the option to export PDFs with the filter

**Comment by LaurentRDC** [comment]
Hello Steffen,

Creating PDF documents is already possible; this is controlled by `pandoc`. Consider the example at the top of the README:

```bash
pandoc --filter pandoc-plot input.md --output output.html
```

This will produce HTML output. If you want to create a PDF instead:

```bash
pandoc --filter pandoc-plot input.md --output output.pdf
```

If this doesn't work, it might be because you don't have all the prerequisites that `pandoc` needs. Take a look at the [installation instructions](https://pandoc.org/installing.html). You will need a LaTeX toolchain.

**Comment by LaurentRDC** [comment]
I'll close this for now, but don't hesitate to re-open if you have difficulties.
